# -*- coding: utf-8 -*-
"""Assignment 1: Word Analogy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqK5GuFQ7TxGSUZHlWvjQ21g6m4i05OQ

### Part I: Data Pre-processing
"""

import pandas as pd

# Download the Google Analogy dataset
!wget http://download.tensorflow.org/data/questions-words.txt

# Preprocess the dataset
file_name = "questions-words"
with open(f"{file_name}.txt", "r") as f:
    data = f.read().splitlines()

# check data from the first 10 entries
for entry in data[:10]:
    print(entry)

# TODO1: Write your code here for processing data to pd.DataFrame
# Please note that the first five mentions of ": " indicate `semantic`,
# and the remaining nine belong to the `syntactic` category.

questions = []
categories = []
sub_categories = []

current_subcategory = None
semantic_count = 0

for line in data:
    line = line.strip()
    if not line:
        continue
    if line.startswith(":"):
        semantic_count += 1
        current_subcategory = line[1:].strip()
        continue
    if current_subcategory:
        questions.append(line)
        sub_categories.append(current_subcategory)
        if semantic_count <= 5:
            categories.append("semantic")
        else:
            categories.append("syntactic")

# Create the dataframe
df = pd.DataFrame(
    {
        "Question": questions,
        "Category": categories,
        "SubCategory": sub_categories,
    }
)

df.head()

df.to_csv(f"{file_name}.csv", index=False)

"""### Part II: Use pre-trained word embeddings
- After finish Part I, you can run Part II code blocks only.


"""

!pip install gensim
import pandas as pd
import numpy as np
import gensim.downloader
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

data = pd.read_csv("questions-words.csv")

MODEL_NAME = "glove-wiki-gigaword-100"
# You can try other models.
# https://radimrehurek.com/gensim/models/word2vec.html#pretrained-models

# Load the pre-trained model (using GloVe vectors here)
model = gensim.downloader.load(MODEL_NAME)
print("The Gensim model loaded successfully!")

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

for analogy in tqdm(data["Question"]):
      # TODO2: Write your code here to use pre-trained word embeddings for getting predictions of the analogy task.
      # You should also preserve the gold answers during iterations for evaluations later.
    words = analogy.split()
    a, b, c, d = words[0], words[1], words[2], words[3]
    golds.append(d)

    # 檢查所有詞是否都在模型中
    if not all(word in model for word in [a, b, c]):
        preds.append(None)
        continue

    # 執行向量運算
    similar_words = model.most_similar(positive=[b, c], negative=[a], topn=1)
    prediction = similar_words[0][0]
    preds.append(prediction)

# 轉成numpy array方便後續處理
golds_np = np.array(golds)
preds_np = np.array(preds)
print(f"處理完成！共 {len(golds)} 個類比問題")
print(f"成功預測: {sum(1 for p in preds if p is not None)} 個")

# Perform evaluations. You do not need to modify this block!!

def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)

golds_np, preds_np = np.array(golds), np.array(preds)
data = pd.read_csv("questions-words.csv")

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category{sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO3: Plot t-SNE for the words in the SUB_CATEGORY `: family`
family_data = data[data["SubCategory"] == "family"]
all_words = set()

for question in family_data["Question"]:
    words = question.split()
    for word in words[:4]:
        if word in model:
            all_words.add(word)

family_words = list(all_words)

word_vectors = []
valid_words = []

for word in family_words:
    if word in model:
        word_vectors.append(model[word])
        valid_words.append(word)

word_vectors = np.array(word_vectors)

# 執行t-SNE降維
tsne = TSNE(n_components=2, random_state=42, perplexity=min(30, len(valid_words)-1))
tsne_results = tsne.fit_transform(word_vectors)

plt.figure(figsize=(15, 10));
plt.scatter(tsne_results[:, 0], tsne_results[:, 1], alpha=0.4, s=90);

for i, word in enumerate(valid_words):
    plt.annotate(word,
                xy=(tsne_results[i, 0], tsne_results[i, 1]),
                xytext=(5, 5), textcoords='offset points',
                fontsize=10, alpha=0.8);

plt.title("Word Relationships from Google Analogy Task");
plt.show();
plt.savefig("word_relationships.png", bbox_inches="tight");

"""### Part III: Train your own word embeddings

### Get the latest English Wikipedia articles and do sampling.
- Usually, we start from Wikipedia dump (https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2). However, the downloading step will take very long. Also, the cleaning step for the Wikipedia corpus ([`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus)) will take much time. Therefore, we provide cleaned files for you.
"""

# Download the split Wikipedia files
# Each file contain 562365 lines (articles).
!pip install gdown
!gdown --folder "https://drive.google.com/drive/folders/1RCan_ieaUW0tXeJzIJzBw_gaZAzCDzKg?usp=sharing" -O .

# Extract the downloaded wiki_texts_parts files.
!gunzip -k wiki_texts_part_*.gz

# Combine the extracted wiki_texts_parts files.
!cat wiki_texts_part_*.txt > wiki_texts_combined.txt

from google.colab import drive
drive.mount('/content/drive')

# Check the first ten lines of the combined file
!head -n 10 wiki_texts_combined.txt

"""Please note that we used the default parameters of [`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus) for cleaning the Wiki raw file. Thus, words with one character were discarded."""

# Now you need to do sampling because the corpus is too big.
# You can further perform analysis with a greater sampling ratio.

import random

wiki_txt_path = "wiki_texts_combined.txt"
output_path = "wiki_sampled_20%_result.txt"

# 預先計算總行數（高效率方法）
print("正在計算總行數...")
with open(wiki_txt_path, "r", encoding="utf-8") as f:
    total_lines = sum(1 for _ in f)
print(f"總共有 {total_lines:,} 篇維基百科文章")

# 計算需要採樣的數量並生成隨機索引
target_samples = int(total_lines * 0.2)  # 20%
print(f"目標採樣: {target_samples:,} 篇文章")

random.seed(42)  # 設定隨機種子確保結果可重現
sample_indices = set(random.sample(range(total_lines), target_samples))

with open(wiki_txt_path, "r", encoding="utf-8") as f:
    with open(output_path, "w", encoding="utf-8") as output_file:
        # TODO4: Sample `20%` Wikipedia articles
        # Write your code here
        sampled_count = 0
        for line_idx, line in enumerate(f):
            if line_idx in sample_indices:
                output_file.write(line)
                sampled_count += 1

print(f"\n 採樣完成！實際採樣了 {sampled_count:,} 篇文章 ({sampled_count/total_lines*100:.2f}%)")

# TODO5: Train your own word embeddings with the sampled articles
# https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec

# 優化版本：解決記憶體和效能問題

import re
import time
import multiprocessing
from collections import Counter
from gensim.models import Word2Vec
from gensim.models.callbacks import CallbackAny2Vec
import numpy as np
import logging
from gensim.models.phrases import Phrases, Phraser
import gc
import psutil
import os

# 設置日誌
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

def monitor_memory():
    """監控記憶體使用情況"""
    process = psutil.Process(os.getpid())
    memory_mb = process.memory_info().rss / 1024 / 1024
    return memory_mb

def pick_vocab_form(word, wv):
    """自動尋找存在於詞彙表的詞彙形式"""
    candidates = [word, word.lower(), word.capitalize(), word.upper()]
    for candidate in candidates:
        if candidate in wv.key_to_index:
            return candidate
    return None

def quick_probe_consistency(wv, n=200):
    """快速檢查隨機詞彙的相似度計算一致性"""
    import random
    words = list(wv.key_to_index.keys())
    sample = random.sample(words, min(n, len(words)))
    success_count = 0

    for word in sample:
        try:
            wv.most_similar(word, topn=1)
            success_count += 1
        except Exception:
            pass

    success_rate = success_count / len(sample) * 100
    print(f"隨機詞彙一致性檢查: {success_count}/{len(sample)} ({success_rate:.1f}%)")

    if success_rate < 95:
        print("⚠️ 警告：詞彙一致性較低，可能存在向量退化問題")

    return success_rate

# 修改參數：減少記憶體使用，提高效率
MEMORY_OPTIMIZED_PARAMS = {
    'input_file': 'wiki_sampled_20%_result.txt',
    'max_lines': None,
    'preserve_pos_patterns': True,
    'preserve_morphology': True,
    'context_quality_filter': True,
    'min_sentence_length': 8,
    'max_sentence_length': 20,  # 縮短句子長度
    'min_word_freq': 20,  # 提高頻率門檻，減少詞彙量
    'preserve_entities': True,

    # Word2Vec 參數 - 記憶體優化版本
    'vector_size': 200,  # 降低維度
    'window': 8,         # 降低窗口大小
    'min_count': 20,     # 提高最小計數，與 min_word_freq 一致
    'epochs': 5,         # 減少訓練輪次
    'sg': 1,
    'negative': 5,       # 降低負採樣
    'sample': 1e-3,      # 增加採樣率
    'alpha': 0.025,
    'min_alpha': 0.0001,
    'workers': max(1, multiprocessing.cpu_count() - 1),  # 使用多核心
    'batch_words': 50000,  # 增加批次大小

    # Phrases 參數 - 記憶體保護
    'enable_phrases': True,
    'phrases_min_count': 25,    # 大幅提高門檻
    'phrases_threshold': 50.0,  # 提高合併門檻
    'max_phrases_memory_gb': 4,  # 記憶體限制

    'ns_exponent': 0.75,
    'model_name': 'memory_optimized.model',
    'vector_name': 'memory_optimized_vectors.bin'
}

class AnalogyPreprocessor:
    def __init__(self):
        self.word_pattern = re.compile(r"\b[a-zA-Z][a-zA-Z\-']{1,24}\b")

        # 精簡停用詞
        self.minimal_stopwords = frozenset([
            'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by',
            'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had',
            'i', 'you', 'he', 'she', 'it', 'we', 'they', 'this', 'that', 'these', 'those'
        ])

        self.entity_patterns = [
            re.compile(r'\b[A-Z][a-zA-Z]*\b'),
            re.compile(r'\b[A-Z]{2,}\b'),
        ]

        self.morphological_patterns = [
            re.compile(r'\b\w+(?:ed|ing|s|es|er|est|ly|tion|sion|ness|ment)\b', re.IGNORECASE),
        ]

    def is_entity_like(self, word):
        return word and len(word) > 1 and word[0].isupper()

    def is_morphologically_important(self, word):
        return any(pattern.match(word) for pattern in self.morphological_patterns)

    def has_semantic_value(self, word):
        word_lower = word.lower()

        if len(word) < 2 or len(word) > 20:
            return False

        if not re.match(r'^[a-zA-Z\-\']+$', word):
            return False

        if word_lower in self.minimal_stopwords:
            return False

        return True

    def preprocess_sentence(self, text):
        if not text or len(text) < 10:
            return []

        words = self.word_pattern.findall(text)
        if len(words) < MEMORY_OPTIMIZED_PARAMS['min_sentence_length']:
            return []

        processed_words = []
        for word in words:
            if self.has_semantic_value(word):
                if self.is_entity_like(word):
                    processed_words.append(word)
                else:
                    processed_words.append(word.lower())

        if len(processed_words) < MEMORY_OPTIMIZED_PARAMS['min_sentence_length']:
            return []

        if len(processed_words) > MEMORY_OPTIMIZED_PARAMS['max_sentence_length']:
            processed_words = processed_words[:MEMORY_OPTIMIZED_PARAMS['max_sentence_length']]

        return processed_words

def create_phrases_safe(sentences, params):
    """記憶體安全的短語創建"""
    if not params.get('enable_phrases', True):
        print("跳過短語合併")
        return sentences

    print(f"記憶體使用: {monitor_memory():.1f} MB")

    # 記憶體檢查
    if monitor_memory() > params.get('max_phrases_memory_gb', 4) * 1024:
        print("⚠️ 記憶體使用過高，跳過短語合併")
        return sentences

    min_count = params.get('phrases_min_count', 50)
    threshold = params.get('phrases_threshold', 50.0)

    print(f"創建短語 (min_count={min_count}, threshold={threshold})")

    try:
        # 分批處理以節省記憶體
        batch_size = 100000
        if len(sentences) > batch_size:
            print(f"大語料庫，分批處理 (batch_size={batch_size})")

            # 訓練在子集上
            sample_sentences = sentences[:batch_size]
            bigram = Phrases(sample_sentences, min_count=min_count, threshold=threshold)
            bigram_phraser = Phraser(bigram)

            # 應用到全部數據
            result_sentences = []
            for i in range(0, len(sentences), batch_size):
                batch = sentences[i:i+batch_size]
                batch_result = [bigram_phraser[sentence] for sentence in batch]
                result_sentences.extend(batch_result)

                if (i // batch_size + 1) % 5 == 0:
                    print(f"處理批次 {i//batch_size + 1}/{(len(sentences)-1)//batch_size + 1}")
                    print(f"記憶體使用: {monitor_memory():.1f} MB")

            return result_sentences

        else:
            bigram = Phrases(sentences, min_count=min_count, threshold=threshold)
            bigram_phraser = Phraser(bigram)
            return [bigram_phraser[sentence] for sentence in sentences]

    except MemoryError:
        print("⚠️ 記憶體不足，跳過短語合併")
        return sentences
    except Exception as e:
        print(f"⚠️ 短語處理失敗: {e}")
        return sentences

def process_corpus_optimized(file_path, params):
    """記憶體優化的語料庫處理"""
    preprocessor = AnalogyPreprocessor()
    start_time = time.time()

    sentences = []
    word_counter = Counter()
    processed_lines = 0
    memory_reports = 0

    print(f"開始處理語料庫: {file_path}")
    print(f"目標參數: min_word_freq={params['min_word_freq']}, min_count={params['min_count']}")

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                if params['max_lines'] and processed_lines >= params['max_lines']:
                    break

                processed_words = preprocessor.preprocess_sentence(line.strip())

                if processed_words:
                    sentences.append(processed_words)
                    word_counter.update(processed_words)

                processed_lines += 1

                # 記憶體和進度監控
                if processed_lines % 100000 == 0:
                    elapsed = time.time() - start_time
                    memory_mb = monitor_memory()
                    print(f"處理 {processed_lines:,} 行 -> {len(sentences):,} 句子 | {elapsed:.1f}s | {memory_mb:.1f} MB")

                    # 記憶體保護
                    if memory_mb > 8000:  # 8GB 限制
                        print("⚠️ 記憶體使用過高，停止讀取更多數據")
                        break

    except Exception as e:
        print(f"讀取文件錯誤: {e}")
        return []

    elapsed = time.time() - start_time
    print(f"\n初步統計:")
    print(f"  總句子數: {len(sentences):,}")
    print(f"  詞彙種類: {len(word_counter):,}")
    print(f"  處理時間: {elapsed:.1f}s")
    print(f"  記憶體使用: {monitor_memory():.1f} MB")

    # 統一過濾門檻
    min_freq = max(params['min_word_freq'], params['min_count'])
    print(f"\n使用統一過濾門檻: {min_freq}")

    # 過濾低頻詞
    vocab_to_keep = {word for word, freq in word_counter.items() if freq >= min_freq}

    print(f"保留詞彙數: {len(vocab_to_keep):,} / {len(word_counter):,}")

    # 重構句子
    filtered_sentences = []
    for sentence in sentences:
        filtered_sentence = [w for w in sentence if w in vocab_to_keep]
        if len(filtered_sentence) >= params['min_sentence_length']:
            filtered_sentences.append(filtered_sentence)

    # 記憶體清理
    del sentences, word_counter
    gc.collect()

    print(f"過濾後句子數: {len(filtered_sentences):,}")
    print(f"記憶體使用: {monitor_memory():.1f} MB")

    # 安全的短語處理
    if params.get('enable_phrases', True):
        filtered_sentences = create_phrases_safe(filtered_sentences, params)
        gc.collect()
        print(f"短語處理後記憶體: {monitor_memory():.1f} MB")

    final_vocab_size = len(set(word for sentence in filtered_sentences for word in sentence))

    print(f"\n最終統計:")
    print(f"  最終句子數: {len(filtered_sentences):,}")
    print(f"  最終詞彙數: {final_vocab_size:,}")
    print(f"  最終記憶體: {monitor_memory():.1f} MB")

    return filtered_sentences

class SimpleCallback(CallbackAny2Vec):
    def __init__(self):
        self.epoch = 0
        self.start_time = time.time()

    def on_epoch_begin(self, model):
        memory_mb = monitor_memory()
        print(f"開始 Epoch {self.epoch + 1}/{MEMORY_OPTIMIZED_PARAMS['epochs']} | 記憶體: {memory_mb:.1f} MB")

    def on_epoch_end(self, model):
        self.epoch += 1
        elapsed = time.time() - self.start_time
        memory_mb = monitor_memory()
        print(f"Epoch {self.epoch} 完成 | 總時間: {elapsed:.1f}s | 記憶體: {memory_mb:.1f} MB")

def train_word2vec_optimized(sentences, params):
    """記憶體優化的 Word2Vec 訓練"""
    print(f"\n開始訓練記憶體優化的 Word2Vec 模型")
    print(f"  句子數量: {len(sentences):,}")
    print(f"  向量維度: {params['vector_size']}")
    print(f"  窗口大小: {params['window']}")
    print(f"  訓練輪次: {params['epochs']}")
    print(f"  工作線程: {params['workers']}")
    print(f"  當前記憶體: {monitor_memory():.1f} MB")

    model_params = {
        'vector_size': params['vector_size'],
        'window': params['window'],
        'min_count': params['min_count'],
        'sg': params['sg'],
        'negative': params['negative'],
        'sample': params['sample'],
        'alpha': params['alpha'],
        'min_alpha': params['min_alpha'],
        'workers': params['workers'],
        'epochs': params['epochs'],
        'batch_words': params['batch_words'],
        'callbacks': [SimpleCallback()],
        'seed': 42,
        'compute_loss': False,
        'ns_exponent': params['ns_exponent']
    }

    start_time = time.time()

    try:
        model = Word2Vec(sentences, **model_params)

        training_time = time.time() - start_time
        vocab_size = len(model.wv.key_to_index)

        print(f"\n=== 訓練完成統計 ===")
        print(f"  詞彙量: {vocab_size:,}")
        print(f"  語料句子數: {model.corpus_count:,}")
        print(f"  語料總詞數: {model.corpus_total_words:,}")
        print(f"  訓練時間: {training_time:.1f}s")
        print(f"  最終記憶體: {monitor_memory():.1f} MB")

        # 快速健康檢查
        print(f"\n=== 模型健康檢查 ===")
        probe_words = ["the", "of", "and", "to", "a", "in", "is", "it", "you", "that"]
        print("高頻詞相似性檢查:")
        for w in probe_words[:5]:  # 只檢查前5個
            if w in model.wv.key_to_index:
                try:
                    similar = [word for word, _ in model.wv.most_similar(w, topn=3)]
                    print(f"  '{w}' -> {similar}")
                    break  # 只要一個成功就OK
                except:
                    pass

        # 向量品質檢查
        norms = np.linalg.norm(model.wv.vectors, axis=1)
        print(f"\n向量統計: 均值={norms.mean():.3f}, 標準差={norms.std():.3f}")

        quick_probe_consistency(model.wv, n=50)  # 減少檢查數量

        return model

    except Exception as e:
        print(f"訓練過程出錯: {e}")
        import traceback
        traceback.print_exc()
        return None

def main():
    """主函數 - 記憶體優化版本"""
    total_start = time.time()

    print("=== 記憶體優化版 Word2Vec 訓練 ===")
    print(f"系統記憶體: {psutil.virtual_memory().total / 1024**3:.1f} GB")
    print(f"可用記憶體: {psutil.virtual_memory().available / 1024**3:.1f} GB")

    try:
        # 1. 處理語料庫
        sentences = process_corpus_optimized(
            MEMORY_OPTIMIZED_PARAMS['input_file'],
            MEMORY_OPTIMIZED_PARAMS
        )

        if not sentences:
            print("沒有有效的句子，結束程序")
            return

        # 2. 訓練模型
        model = train_word2vec_optimized(sentences, MEMORY_OPTIMIZED_PARAMS)

        if model is None:
            print("模型訓練失敗，結束程序")
            return

        # 3. 簡化評估（節省記憶體）
        print(f"\n=== 快速類比測試 ===")
        simple_tests = [
            ('good', 'better', 'bad', 'worse'),
            ('king', 'queen', 'man', 'woman'),
        ]

        successful = 0
        for a, b, c, expected in simple_tests:
            vocab_a = pick_vocab_form(a, model.wv)
            vocab_b = pick_vocab_form(b, model.wv)
            vocab_c = pick_vocab_form(c, model.wv)
            vocab_expected = pick_vocab_form(expected, model.wv)

            if all(v is not None for v in [vocab_a, vocab_b, vocab_c, vocab_expected]):
                try:
                    result = model.wv.most_similar(
                        positive=[vocab_b, vocab_c],
                        negative=[vocab_a],
                        topn=3
                    )
                    predicted_words = [word for word, score in result]

                    if vocab_expected in predicted_words:
                        print(f"✓ {vocab_a}:{vocab_b} :: {vocab_c}:{vocab_expected}")
                        successful += 1
                    else:
                        print(f"✗ {vocab_a}:{vocab_b} :: {vocab_c}:{vocab_expected} -> {predicted_words[0]}")
                except:
                    print(f"✗ {vocab_a}:{vocab_b} :: {vocab_c}:{vocab_expected} - 計算錯誤")

        # 4. 保存模型
        model.save(MEMORY_OPTIMIZED_PARAMS['model_name'])
        model.wv.save_word2vec_format(MEMORY_OPTIMIZED_PARAMS['vector_name'], binary=True)

        kv_filename = MEMORY_OPTIMIZED_PARAMS['model_name'].replace('.model', '.kv')
        model.wv.save(kv_filename)

        print(f"\n模型已保存:")
        print(f"  完整模型: {MEMORY_OPTIMIZED_PARAMS['model_name']}")
        print(f"  二進制向量: {MEMORY_OPTIMIZED_PARAMS['vector_name']}")
        print(f"  KeyedVectors: {kv_filename}")

        total_time = time.time() - total_start
        print(f"\n總執行時間: {total_time:.1f}s")
        print(f"最終記憶體使用: {monitor_memory():.1f} MB")

    except Exception as e:
        print(f"程序執行錯誤: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()

data = pd.read_csv("questions-words.csv")

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []
from gensim.models import Word2Vec
from tqdm import tqdm
import numpy as np

# 載入你訓練的模型
model = Word2Vec.load("memory_optimized.model")  # 使用你的模型文件名
print(f"載入模型完成，詞彙量: {len(model.wv.key_to_index):,}")

def pick_vocab_form(word, wv):
    """自動尋找存在於詞彙表的詞彙形式（與你的訓練代碼一致）"""
    candidates = [word, word.lower(), word.capitalize(), word.upper()]
    for candidate in candidates:
        if candidate in wv.key_to_index:
            return candidate
    return None

def post_process_prediction(prediction, gold_answer):
    """後處理預測結果，調整大小寫以匹配金標準答案的格式"""
    if prediction is None or gold_answer is None:
        return prediction

    # 如果金標準答案是首字母大寫，將預測也調整為首字母大寫
    if gold_answer[0].isupper():
        return prediction.capitalize()
    # 如果金標準答案是全大寫，將預測也調整為全大寫
    elif gold_answer.isupper():
        return prediction.upper()
    # 如果金標準答案是全小寫，將預測也調整為全小寫
    elif gold_answer.islower():
        return prediction.lower()
    else:
        # 保持原樣
        return prediction

for analogy in tqdm(data["Question"], desc="處理類比任務"):
    try:
        # 判斷輸入格式並相應處理
        if "::" in analogy:
            # 標準格式：word_A:word_B::word_C:word_D
            parts = analogy.split("::")
            if len(parts) != 2:
                preds.append(None)
                golds.append(None)
                continue

            left_part = parts[0].split(":")
            right_part = parts[1].split(":")

            if len(left_part) != 2 or len(right_part) != 2:
                preds.append(None)
                golds.append(None)
                continue

            word_A, word_B = left_part[0].strip(), left_part[1].strip()
            word_C, word_D = right_part[0].strip(), right_part[1].strip()

        else:
            # 空格分隔格式：word_A word_B word_C word_D
            words = analogy.split()
            if len(words) != 4:
                preds.append(None)
                golds.append(None)
                continue
            word_A, word_B, word_C, word_D = words[0], words[1], words[2], words[3]

        # 保存金標準答案
        golds.append(word_D)

        # 使用與訓練代碼一致的詞彙查找方式
        vocab_A = pick_vocab_form(word_A, model.wv)
        vocab_B = pick_vocab_form(word_B, model.wv)
        vocab_C = pick_vocab_form(word_C, model.wv)

        # 檢查所需詞彙是否都在模型中
        if not all(word is not None for word in [vocab_A, vocab_B, vocab_C]):
            preds.append(None)
            continue

        # 使用向量運算: word_D ≈ word_B - word_A + word_C
        try:
            similar_words = model.wv.most_similar(
                positive=[vocab_B, vocab_C],
                negative=[vocab_A],
                topn=10  # 取更多候選，提高準確率
            )

            # 取最相似的詞作為預測
            predicted_word = similar_words[0][0]

            # 🎯 新增：後處理預測結果，調整大小寫格式
            processed_prediction = post_process_prediction(predicted_word, word_D)
            preds.append(processed_prediction)

        except KeyError:
            preds.append(None)
        except Exception as e:
            print(f"處理類比 '{analogy}' 時出錯: {e}")
            preds.append(None)

    except Exception as e:
        print(f"解析類比 '{analogy}' 時出錯: {e}")
        preds.append(None)
        golds.append(None)

# 統計結果
total_questions = len(preds)
valid_predictions = sum(1 for p in preds if p is not None)
correct_predictions = sum(1 for p, g in zip(preds, golds) if p is not None and g is not None and p == g)

print(f"\n類比任務統計:")
print(f"總題數: {total_questions}")
print(f"有效預測: {valid_predictions} ({valid_predictions/total_questions*100:.1f}%)")
if valid_predictions > 0:
    print(f"準確預測: {correct_predictions} ({correct_predictions/valid_predictions*100:.1f}% of valid)")
print(f"整體準確率: {correct_predictions/total_questions*100:.1f}%")

# 顯示一些例子
print(f"\n預測範例 (前10個有效預測):")
shown = 0
for i in range(len(preds)):
    if preds[i] is not None and golds[i] is not None and shown < 10:
        status = "✓" if preds[i] == golds[i] else "✗"
        print(f"{status} 預測: {preds[i]}, 正解: {golds[i]}")
        shown += 1

# 轉換為numpy array（如果需要後續處理）
golds_np = np.array(golds)
preds_np = np.array(preds)

# Collect words from Google Analogy dataset
SUB_CATEGORY = ": family"

# TODO7: Plot t-SNE for the words in the SUB_CATEGORY `: family`

# Collect words from Google Analogy dataset
import matplotlib.pyplot as plt
import numpy as np
from sklearn.manifold import TSNE
from gensim.models import Word2Vec

# 載入你的訓練模型
model = Word2Vec.load("memory_optimized.model")
print(f"載入模型完成，詞彙量: {len(model.wv.key_to_index):,}")

def pick_vocab_form(word, wv):
    """尋找存在於詞彙表的詞彙形式"""
    candidates = [word, word.lower(), word.capitalize(), word.upper()]
    for candidate in candidates:
        if candidate in wv.key_to_index:
            return candidate
    return None

# 使用 SubCategory 過濾 family 類別
family_data = data[data["SubCategory"] == "family"]
print(f"找到 {len(family_data)} 個 family 類別的問題")

# 顯示一些樣本
print("Family 類別問題樣本:")
for i, question in enumerate(family_data["Question"][:5]):
    print(f"  {i+1}. {question}")

# 收集所有在模型中存在的詞彙
all_words = set()
for question in family_data["Question"]:
    words = question.split()
    for word in words[:4]:  # 只取前4個詞
        model_word = pick_vocab_form(word, model.wv)
        if model_word is not None:
            all_words.add(word)  # 保存原始詞彙形式用於顯示

family_words = list(all_words)
print(f"收集到 {len(family_words)} 個在模型中存在的詞彙")

# 準備詞向量
word_vectors = []
valid_words = []

for word in family_words:
    model_word = pick_vocab_form(word, model.wv)
    if model_word is not None:
        word_vectors.append(model.wv[model_word])
        valid_words.append(word)

print(f"最終有效詞彙數: {len(valid_words)}")
print(f"有效詞彙: {valid_words[:10]}{'...' if len(valid_words) > 10 else ''}")

# 執行 t-SNE 降維
word_vectors = np.array(word_vectors)
perplexity = min(30, len(valid_words)-1)
tsne = TSNE(n_components=2, random_state=42, perplexity=perplexity, max_iter=1000)
tsne_results = tsne.fit_transform(word_vectors)

# 創建可視化
plt.figure(figsize=(15, 10))
plt.scatter(tsne_results[:, 0], tsne_results[:, 1], alpha=0.6, s=100, c='skyblue', edgecolors='navy')

# 添加詞彙標籤
for i, word in enumerate(valid_words):
    plt.annotate(word,
                xy=(tsne_results[i, 0], tsne_results[i, 1]),
                xytext=(5, 5), textcoords='offset points',
                fontsize=11, alpha=0.8,
                bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.7))


plt.xlabel("t-SNE Dimension 1", fontsize=12)
plt.ylabel("t-SNE Dimension 2", fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.title("Word Relationships from Google Analogy Task")
plt.show()
plt.savefig("word_relationships.png", bbox_inches="tight")
